var slogan = [
  "Action Gets Results",
  "Against All Odds",
  "All Is Well",
  "Always Add Value",
  "Appreciate The Moment",
  "Aspire To Inspire",
  "Be A Boss",
  "Be A Giver",
  "Be Here Now",
  "Be Obsessively Grateful",
  "Be The Change",
  "Because I Can",
  "Believe In Yourself",
  "Bravery In Fear",
  "Can't Stop Now",
  "Change Is Good ",
  "Choose To Shine",
  "Collect Beautiful Moments",
  "Connect With Nature",
  "Conquer From Within ",
  "Count Your Blessings",
  "Decisiveness In Doubt",
  "Design Your Life",
  "Develop Your Strength",
  "Do Amazing Things",
  "Do It Now",
  "Do Your Best",
  "Don't Set Limitations",
  "Don't Be Afraid",
  "Dream, Believe, Achieve",
  "Dreams Come True",
  "Embrace The Journey",
  "Enjoy Every Moment",
  "Every Moment Matters",
  "Feed Your Soul",
  "Focus And Win",
  "Genius Is Patience",
  "Get Enough Sleep",
  "Get Fresh Air",
  "Give Real Value",
  "Go All Out",
  "Go For It",
  "Good Vibes Only",
  "Happiness Is Success",
  "Health Is Wealth",
  "Hit The Goals",
  "Inches Make Champions",
  "Innovation With Imagination",
  "It Is Possible",
  "Just Do It",
  "Keep It Cool ",
  "Keep Moving Forward",
  "Keep On Shining",
  "Know Thy Self",
  "Knowledge Is Power",
  "Learn From Yesterday",
  "Learn Something New",
  "Let It Go",
  "Life Won't Wait",
  "Live And Learn",
  "Live For Others",
  "Live In Possibility",
  "Live Your Potential",
  "Loyalty Is Royalty",
  "Maintain Your Integrity",
  "Make It Happen",
  "Never Give Up",
  "Never Look Back ",
  "Never Too Late",
  "Nobody Is Perfect",
  "Now Or Never",
  "Organize Your Life",
  "Persistence In Everything",
  "Prove Them Wrong",
  "Pursue Your Passion",
  "Recovery Is Possible",
  "Remember To Live",
  "Roll With It",
  "See The Good",
  "Seize The Day",
  "Shine Your Light",
  "Simplify Your Life",
  "Speak The Truth",
  "Stay The Course",
  "Stop Underestimating Yourself",
  "Success Breads Success",
  "Success Is Yours",
  "Take Action Now",
  "Take The Risk",
  "Try Something New",
  "Use Your Wings",
  "Volunteer Your Time",
  "Winners Never Quit",
  "You Are Capable",
  "You Are Enough",
  "You Got This",
  "<a href=\"#\" style=\"color: #F012BE; text-decoration: none;\" data-bs-toggle=\"modal\" data-bs-target=\"#memories\">♥ In Loving Memory ♥</a>",
];

//Display a random quote
document.getElementById("slogan").innerHTML = slogan[Math.floor(Math.random() * slogan.length)];
//Uncomment below for memories overwrite
//document.getElementById("slogan").innerHTML = slogan[96];
